services:
  price-service:
    image: "evleria/price-service:v0.0.1"
    depends_on:
      - redis
    environment:
      - ENVIRONMENT=prod
      - REDIS_HOST=redis
      - GENERATION_RATE=1s

  position-service-0:
    build: .
    ports:
      - "6001:6000"
    depends_on:
      - postgres
      - redis
    command: sh -c "/wait && /server"
    environment:
      - ENVIRONMENT=prod
      - POSTGRES_HOST=postgres
      - REDIS_HOST=redis
      - WAIT_HOSTS=postgres:5432

  position-service-1:
    build: .
    ports:
      - "6002:6000"
    depends_on:
      - postgres
      - redis
    command: sh -c "/wait && /server"
    environment:
      - ENVIRONMENT=prod
      - POSTGRES_HOST=postgres
      - REDIS_HOST=redis
      - WAIT_HOSTS=postgres:5432

  redis:
    image: "redis:6-alpine"
    hostname: redis
    ports:
      - "6379:6379"
    command: sh -c "redis-server --appendonly yes"
    volumes:
      - redis-data:/data

  postgres:
    image: "postgres:13-alpine"
    hostname: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
    volumes:
      - pg-data:/var/lib/postgresql/data

volumes:
  redis-data:
  pg-data:
