services:
  backend-0:
  build: .
  ports:
    - "5001:5000"
    - "6001:6000"
    depends_on:
      -redis
  environment:
    - REDIS_HOST=redis

  backend-1:
    build: .
    ports:
      - "5002:5000"
      - "6002:6000"
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis


  redis:
    image: "redis:6-alpine"
    hostname: redis
    ports:
      - "6379:6379"
    command: sh -c "redis-server --appendonly yes"
    volumes:
      - redis-data:/data

volumes:
  redis-data:
  rabbitmq-data: