services:
  position-service-0:
    build: .
    ports:
      - "6001:6000"
    depends_on:
      - postgres
    command: sh -c "/wait && /server"
    environment:
      - ENVIRONMENT=prod
      - PRICE_SERVICE_HOST=price-service
      - POSTGRES_HOST=postgres
      - WAIT_HOSTS=postgres:5432

  position-service-1:
    build: .
    ports:
      - "6002:6000"
    depends_on:
      - postgres
    command: sh -c "/wait && /server"
    environment:
      - ENVIRONMENT=prod
      - PRICE_SERVICE_HOST=price-service
      - POSTGRES_HOST=postgres
      - WAIT_HOSTS=postgres:5432

  price-service:
    image: "evleria/price-service:v0.0.3"
    ports:
      - "6003:6000"
    environment:
      - ENVIRONMENT=prod
      - GENERATION_RATE=100ms

  postgres:
    image: "postgres:13-alpine"
    hostname: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
    volumes:
      - pg-data:/var/lib/postgresql/data

volumes:
  pg-data:
