services:
  backend-0:
   build: .
   ports:
    - "5001:5000"
    - "6001:6000"
   depends_on:
    - postgres
    - redis
   command: sh -c "/wait && /server"
   environment:
    - POSTGRES_HOST=postgres
    - REDIS_HOST=redis
    - ENVIRONMENT=prod
    - WAIT_HOSTS=postgres:5432

  backend-1:
    build: .
    ports:
      - "5002:5000"
      - "6002:6000"
    depends_on:
    - postgres
    - redis
    environment:
    - POSTGRES_HOST=postgres
    - REDIS_HOST=redis
    - ENVIRONMENT=prod
    - GENERATE_PRICES=false
    - WAIT_HOSTS=postgres:5432

  redis:
    image: "redis:6-alpine"
    hostname: redis
    ports:
      - "6379:6379"
    command: sh -c "redis-server --appendonly yes"
    volumes:
      - redis-data:/data

  postgres:
    image: "postgres:13-alpine"
    hostname: postgres
    ports:
      - "5432:5432"
    environment:
      - POSTGRES_HOST_AUTH_METHOD=trust
    volumes:
      - pg-data:/var/lib/postgresql/data

volumes:
  redis-data:
  pg-data:
