// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.26.0
// 	protoc        v3.6.1
// source: price_service.proto

package pb

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AddPositionRequest struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	InitialPrice float64 `protobuf:"fixed64,1,opt,name=initial_price,json=initialPrice,proto3" json:"initial_price,omitempty"`
}

func (x *AddPositionRequest) Reset() {
	*x = AddPositionRequest{}
	if protoimpl.UnsafeEnabled {
		mi := &file_price_service_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddPositionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddPositionRequest) ProtoMessage() {}

func (x *AddPositionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_price_service_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddPositionRequest.ProtoReflect.Descriptor instead.
func (*AddPositionRequest) Descriptor() ([]byte, []int) {
	return file_price_service_proto_rawDescGZIP(), []int{0}
}

func (x *AddPositionRequest) GetInitialPrice() float64 {
	if x != nil {
		return x.InitialPrice
	}
	return 0
}

type AddPositionResponse struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	PositionId int64 `protobuf:"varint,1,opt,name=position_id,json=positionId,proto3" json:"position_id,omitempty"`
}

func (x *AddPositionResponse) Reset() {
	*x = AddPositionResponse{}
	if protoimpl.UnsafeEnabled {
		mi := &file_price_service_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *AddPositionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AddPositionResponse) ProtoMessage() {}

func (x *AddPositionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_price_service_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AddPositionResponse.ProtoReflect.Descriptor instead.
func (*AddPositionResponse) Descriptor() ([]byte, []int) {
	return file_price_service_proto_rawDescGZIP(), []int{1}
}

func (x *AddPositionResponse) GetPositionId() int64 {
	if x != nil {
		return x.PositionId
	}
	return 0
}

var File_price_service_proto protoreflect.FileDescriptor

var file_price_service_proto_rawDesc = []byte{
	0x0a, 0x13, 0x70, 0x72, 0x69, 0x63, 0x65, 0x5f, 0x73, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x2e,
	0x70, 0x72, 0x6f, 0x74, 0x6f, 0x22, 0x39, 0x0a, 0x12, 0x41, 0x64, 0x64, 0x50, 0x6f, 0x73, 0x69,
	0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x12, 0x23, 0x0a, 0x0d, 0x69,
	0x6e, 0x69, 0x74, 0x69, 0x61, 0x6c, 0x5f, 0x70, 0x72, 0x69, 0x63, 0x65, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x01, 0x52, 0x0c, 0x69, 0x6e, 0x69, 0x74, 0x69, 0x61, 0x6c, 0x50, 0x72, 0x69, 0x63, 0x65,
	0x22, 0x36, 0x0a, 0x13, 0x41, 0x64, 0x64, 0x50, 0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x52,
	0x65, 0x73, 0x70, 0x6f, 0x6e, 0x73, 0x65, 0x12, 0x1f, 0x0a, 0x0b, 0x70, 0x6f, 0x73, 0x69, 0x74,
	0x69, 0x6f, 0x6e, 0x5f, 0x69, 0x64, 0x18, 0x01, 0x20, 0x01, 0x28, 0x03, 0x52, 0x0a, 0x70, 0x6f,
	0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x49, 0x64, 0x32, 0x4c, 0x0a, 0x0e, 0x42, 0x69, 0x64, 0x64,
	0x69, 0x6e, 0x67, 0x53, 0x65, 0x72, 0x76, 0x69, 0x63, 0x65, 0x12, 0x3a, 0x0a, 0x0b, 0x41, 0x64,
	0x64, 0x50, 0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x13, 0x2e, 0x41, 0x64, 0x64, 0x50,
	0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x71, 0x75, 0x65, 0x73, 0x74, 0x1a, 0x14,
	0x2e, 0x41, 0x64, 0x64, 0x50, 0x6f, 0x73, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x52, 0x65, 0x73, 0x70,
	0x6f, 0x6e, 0x73, 0x65, 0x22, 0x00, 0x42, 0x05, 0x5a, 0x03, 0x2f, 0x70, 0x62, 0x62, 0x06, 0x70,
	0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_price_service_proto_rawDescOnce sync.Once
	file_price_service_proto_rawDescData = file_price_service_proto_rawDesc
)

func file_price_service_proto_rawDescGZIP() []byte {
	file_price_service_proto_rawDescOnce.Do(func() {
		file_price_service_proto_rawDescData = protoimpl.X.CompressGZIP(file_price_service_proto_rawDescData)
	})
	return file_price_service_proto_rawDescData
}

var file_price_service_proto_msgTypes = make([]protoimpl.MessageInfo, 2)
var file_price_service_proto_goTypes = []interface{}{
	(*AddPositionRequest)(nil),  // 0: AddPositionRequest
	(*AddPositionResponse)(nil), // 1: AddPositionResponse
}
var file_price_service_proto_depIdxs = []int32{
	0, // 0: BiddingService.AddPosition:input_type -> AddPositionRequest
	1, // 1: BiddingService.AddPosition:output_type -> AddPositionResponse
	1, // [1:2] is the sub-list for method output_type
	0, // [0:1] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_price_service_proto_init() }
func file_price_service_proto_init() {
	if File_price_service_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_price_service_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddPositionRequest); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_price_service_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*AddPositionResponse); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_price_service_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   2,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_price_service_proto_goTypes,
		DependencyIndexes: file_price_service_proto_depIdxs,
		MessageInfos:      file_price_service_proto_msgTypes,
	}.Build()
	File_price_service_proto = out.File
	file_price_service_proto_rawDesc = nil
	file_price_service_proto_goTypes = nil
	file_price_service_proto_depIdxs = nil
}
